kind: Deployment
apiVersion: apps/v1
metadata:
  name: springboot-actuator-demo
  namespace: springboot-demo
  labels:
    app: springboot-actuator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-actuator-demo
  template:
    metadata:
      labels:
        app: springboot-actuator-demo
    spec:
      containers:
        - name: springboot-actuator-demo
          image: 'frezes/springboot-actuator-demo:latest'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
