kind: Service
apiVersion: v1
metadata:
  name: springboot-actuator-demo
  namespace: springboot-demo
  labels:
    app: springboot-actuator-demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: springboot-actuator-demo